### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by secondtruth** [seabreeze-project/seabreeze#9]
Implement a Script Runner feature in Seabreeze to run predefined commands within containers and on the host. This feature will streamline task automation and management across different environments.

## Details

The Script Runner will:

- Execute predefined commands either within Docker containers (individual or assigned to a service) or directly on the host machine.
- Run commands inside containers using the Docker API for better integration and control.
- Allow configuration of the working directory, user, and environment variables for each script.

### Example Configuration

Scripts will be defined in the project configuration as follows:

```yaml
scripts:
  test:
    command: npm test
    target: "service:app"
    workdir: "/usr/src/app"
    environment:
      NODE_ENV: "test"
    user: "user"
  build:
    command: make build
    target: "host"
    workdir: "/home/user/project"
    environment:
      BUILD_ENV: "production"
```

## Tasks

- [X] Implement basic library
- [X] Implement command
- [ ] Support running scripts on the host as specific user on Windows
- [ ] Use Docker API instead of calling the `docker` command to run scripts
